// Generated by CIRCT firtool-1.62.1
module DotProduct(
  input  [7:0]  io_a_0,
                io_a_1,
                io_a_2,
                io_b_0,
                io_b_1,
                io_b_2,
  output [31:0] io_result
);

  wire [15:0] _io_result_T_3 =
    {{8{io_a_0[7]}}, io_a_0} * {{8{io_b_0[7]}}, io_b_0} + {{8{io_a_1[7]}}, io_a_1}
    * {{8{io_b_1[7]}}, io_b_1} + {{8{io_a_2[7]}}, io_a_2} * {{8{io_b_2[7]}}, io_b_2};
  assign io_result = {{16{_io_result_T_3[15]}}, _io_result_T_3};
endmodule

module PointwiseConvolution(
  input         clock,
                reset,
  input  [7:0]  io_input_0_0_0,
                io_input_0_0_1,
                io_input_0_0_2,
                io_input_0_0_3,
                io_input_0_0_4,
                io_input_0_1_0,
                io_input_0_1_1,
                io_input_0_1_2,
                io_input_0_1_3,
                io_input_0_1_4,
                io_input_0_2_0,
                io_input_0_2_1,
                io_input_0_2_2,
                io_input_0_2_3,
                io_input_0_2_4,
                io_input_0_3_0,
                io_input_0_3_1,
                io_input_0_3_2,
                io_input_0_3_3,
                io_input_0_3_4,
                io_input_0_4_0,
                io_input_0_4_1,
                io_input_0_4_2,
                io_input_0_4_3,
                io_input_0_4_4,
                io_input_1_0_0,
                io_input_1_0_1,
                io_input_1_0_2,
                io_input_1_0_3,
                io_input_1_0_4,
                io_input_1_1_0,
                io_input_1_1_1,
                io_input_1_1_2,
                io_input_1_1_3,
                io_input_1_1_4,
                io_input_1_2_0,
                io_input_1_2_1,
                io_input_1_2_2,
                io_input_1_2_3,
                io_input_1_2_4,
                io_input_1_3_0,
                io_input_1_3_1,
                io_input_1_3_2,
                io_input_1_3_3,
                io_input_1_3_4,
                io_input_1_4_0,
                io_input_1_4_1,
                io_input_1_4_2,
                io_input_1_4_3,
                io_input_1_4_4,
                io_input_2_0_0,
                io_input_2_0_1,
                io_input_2_0_2,
                io_input_2_0_3,
                io_input_2_0_4,
                io_input_2_1_0,
                io_input_2_1_1,
                io_input_2_1_2,
                io_input_2_1_3,
                io_input_2_1_4,
                io_input_2_2_0,
                io_input_2_2_1,
                io_input_2_2_2,
                io_input_2_2_3,
                io_input_2_2_4,
                io_input_2_3_0,
                io_input_2_3_1,
                io_input_2_3_2,
                io_input_2_3_3,
                io_input_2_3_4,
                io_input_2_4_0,
                io_input_2_4_1,
                io_input_2_4_2,
                io_input_2_4_3,
                io_input_2_4_4,
                io_weights_0_0_0_0,
                io_weights_0_1_0_0,
                io_weights_0_2_0_0,
                io_weights_1_0_0_0,
                io_weights_1_1_0_0,
                io_weights_1_2_0_0,
                io_weights_2_0_0_0,
                io_weights_2_1_0_0,
                io_weights_2_2_0_0,
                io_weights_3_0_0_0,
                io_weights_3_1_0_0,
                io_weights_3_2_0_0,
  output [31:0] io_output_0_0_0,
                io_output_0_0_1,
                io_output_0_0_2,
                io_output_0_0_3,
                io_output_0_0_4,
                io_output_0_1_0,
                io_output_0_1_1,
                io_output_0_1_2,
                io_output_0_1_3,
                io_output_0_1_4,
                io_output_0_2_0,
                io_output_0_2_1,
                io_output_0_2_2,
                io_output_0_2_3,
                io_output_0_2_4,
                io_output_0_3_0,
                io_output_0_3_1,
                io_output_0_3_2,
                io_output_0_3_3,
                io_output_0_3_4,
                io_output_0_4_0,
                io_output_0_4_1,
                io_output_0_4_2,
                io_output_0_4_3,
                io_output_0_4_4,
                io_output_1_0_0,
                io_output_1_0_1,
                io_output_1_0_2,
                io_output_1_0_3,
                io_output_1_0_4,
                io_output_1_1_0,
                io_output_1_1_1,
                io_output_1_1_2,
                io_output_1_1_3,
                io_output_1_1_4,
                io_output_1_2_0,
                io_output_1_2_1,
                io_output_1_2_2,
                io_output_1_2_3,
                io_output_1_2_4,
                io_output_1_3_0,
                io_output_1_3_1,
                io_output_1_3_2,
                io_output_1_3_3,
                io_output_1_3_4,
                io_output_1_4_0,
                io_output_1_4_1,
                io_output_1_4_2,
                io_output_1_4_3,
                io_output_1_4_4,
                io_output_2_0_0,
                io_output_2_0_1,
                io_output_2_0_2,
                io_output_2_0_3,
                io_output_2_0_4,
                io_output_2_1_0,
                io_output_2_1_1,
                io_output_2_1_2,
                io_output_2_1_3,
                io_output_2_1_4,
                io_output_2_2_0,
                io_output_2_2_1,
                io_output_2_2_2,
                io_output_2_2_3,
                io_output_2_2_4,
                io_output_2_3_0,
                io_output_2_3_1,
                io_output_2_3_2,
                io_output_2_3_3,
                io_output_2_3_4,
                io_output_2_4_0,
                io_output_2_4_1,
                io_output_2_4_2,
                io_output_2_4_3,
                io_output_2_4_4,
                io_output_3_0_0,
                io_output_3_0_1,
                io_output_3_0_2,
                io_output_3_0_3,
                io_output_3_0_4,
                io_output_3_1_0,
                io_output_3_1_1,
                io_output_3_1_2,
                io_output_3_1_3,
                io_output_3_1_4,
                io_output_3_2_0,
                io_output_3_2_1,
                io_output_3_2_2,
                io_output_3_2_3,
                io_output_3_2_4,
                io_output_3_3_0,
                io_output_3_3_1,
                io_output_3_3_2,
                io_output_3_3_3,
                io_output_3_3_4,
                io_output_3_4_0,
                io_output_3_4_1,
                io_output_3_4_2,
                io_output_3_4_3,
                io_output_3_4_4
);

  DotProduct io_output_0_0_0_dot (
    .io_a_0    (io_input_0_0_0),
    .io_a_1    (io_input_1_0_0),
    .io_a_2    (io_input_2_0_0),
    .io_b_0    (io_weights_0_0_0_0),
    .io_b_1    (io_weights_0_1_0_0),
    .io_b_2    (io_weights_0_2_0_0),
    .io_result (io_output_0_0_0)
  );
  DotProduct io_output_0_0_1_dot (
    .io_a_0    (io_input_0_0_1),
    .io_a_1    (io_input_1_0_1),
    .io_a_2    (io_input_2_0_1),
    .io_b_0    (io_weights_0_0_0_0),
    .io_b_1    (io_weights_0_1_0_0),
    .io_b_2    (io_weights_0_2_0_0),
    .io_result (io_output_0_0_1)
  );
  DotProduct io_output_0_0_2_dot (
    .io_a_0    (io_input_0_0_2),
    .io_a_1    (io_input_1_0_2),
    .io_a_2    (io_input_2_0_2),
    .io_b_0    (io_weights_0_0_0_0),
    .io_b_1    (io_weights_0_1_0_0),
    .io_b_2    (io_weights_0_2_0_0),
    .io_result (io_output_0_0_2)
  );
  DotProduct io_output_0_0_3_dot (
    .io_a_0    (io_input_0_0_3),
    .io_a_1    (io_input_1_0_3),
    .io_a_2    (io_input_2_0_3),
    .io_b_0    (io_weights_0_0_0_0),
    .io_b_1    (io_weights_0_1_0_0),
    .io_b_2    (io_weights_0_2_0_0),
    .io_result (io_output_0_0_3)
  );
  DotProduct io_output_0_0_4_dot (
    .io_a_0    (io_input_0_0_4),
    .io_a_1    (io_input_1_0_4),
    .io_a_2    (io_input_2_0_4),
    .io_b_0    (io_weights_0_0_0_0),
    .io_b_1    (io_weights_0_1_0_0),
    .io_b_2    (io_weights_0_2_0_0),
    .io_result (io_output_0_0_4)
  );
  DotProduct io_output_0_1_0_dot (
    .io_a_0    (io_input_0_1_0),
    .io_a_1    (io_input_1_1_0),
    .io_a_2    (io_input_2_1_0),
    .io_b_0    (io_weights_0_0_0_0),
    .io_b_1    (io_weights_0_1_0_0),
    .io_b_2    (io_weights_0_2_0_0),
    .io_result (io_output_0_1_0)
  );
  DotProduct io_output_0_1_1_dot (
    .io_a_0    (io_input_0_1_1),
    .io_a_1    (io_input_1_1_1),
    .io_a_2    (io_input_2_1_1),
    .io_b_0    (io_weights_0_0_0_0),
    .io_b_1    (io_weights_0_1_0_0),
    .io_b_2    (io_weights_0_2_0_0),
    .io_result (io_output_0_1_1)
  );
  DotProduct io_output_0_1_2_dot (
    .io_a_0    (io_input_0_1_2),
    .io_a_1    (io_input_1_1_2),
    .io_a_2    (io_input_2_1_2),
    .io_b_0    (io_weights_0_0_0_0),
    .io_b_1    (io_weights_0_1_0_0),
    .io_b_2    (io_weights_0_2_0_0),
    .io_result (io_output_0_1_2)
  );
  DotProduct io_output_0_1_3_dot (
    .io_a_0    (io_input_0_1_3),
    .io_a_1    (io_input_1_1_3),
    .io_a_2    (io_input_2_1_3),
    .io_b_0    (io_weights_0_0_0_0),
    .io_b_1    (io_weights_0_1_0_0),
    .io_b_2    (io_weights_0_2_0_0),
    .io_result (io_output_0_1_3)
  );
  DotProduct io_output_0_1_4_dot (
    .io_a_0    (io_input_0_1_4),
    .io_a_1    (io_input_1_1_4),
    .io_a_2    (io_input_2_1_4),
    .io_b_0    (io_weights_0_0_0_0),
    .io_b_1    (io_weights_0_1_0_0),
    .io_b_2    (io_weights_0_2_0_0),
    .io_result (io_output_0_1_4)
  );
  DotProduct io_output_0_2_0_dot (
    .io_a_0    (io_input_0_2_0),
    .io_a_1    (io_input_1_2_0),
    .io_a_2    (io_input_2_2_0),
    .io_b_0    (io_weights_0_0_0_0),
    .io_b_1    (io_weights_0_1_0_0),
    .io_b_2    (io_weights_0_2_0_0),
    .io_result (io_output_0_2_0)
  );
  DotProduct io_output_0_2_1_dot (
    .io_a_0    (io_input_0_2_1),
    .io_a_1    (io_input_1_2_1),
    .io_a_2    (io_input_2_2_1),
    .io_b_0    (io_weights_0_0_0_0),
    .io_b_1    (io_weights_0_1_0_0),
    .io_b_2    (io_weights_0_2_0_0),
    .io_result (io_output_0_2_1)
  );
  DotProduct io_output_0_2_2_dot (
    .io_a_0    (io_input_0_2_2),
    .io_a_1    (io_input_1_2_2),
    .io_a_2    (io_input_2_2_2),
    .io_b_0    (io_weights_0_0_0_0),
    .io_b_1    (io_weights_0_1_0_0),
    .io_b_2    (io_weights_0_2_0_0),
    .io_result (io_output_0_2_2)
  );
  DotProduct io_output_0_2_3_dot (
    .io_a_0    (io_input_0_2_3),
    .io_a_1    (io_input_1_2_3),
    .io_a_2    (io_input_2_2_3),
    .io_b_0    (io_weights_0_0_0_0),
    .io_b_1    (io_weights_0_1_0_0),
    .io_b_2    (io_weights_0_2_0_0),
    .io_result (io_output_0_2_3)
  );
  DotProduct io_output_0_2_4_dot (
    .io_a_0    (io_input_0_2_4),
    .io_a_1    (io_input_1_2_4),
    .io_a_2    (io_input_2_2_4),
    .io_b_0    (io_weights_0_0_0_0),
    .io_b_1    (io_weights_0_1_0_0),
    .io_b_2    (io_weights_0_2_0_0),
    .io_result (io_output_0_2_4)
  );
  DotProduct io_output_0_3_0_dot (
    .io_a_0    (io_input_0_3_0),
    .io_a_1    (io_input_1_3_0),
    .io_a_2    (io_input_2_3_0),
    .io_b_0    (io_weights_0_0_0_0),
    .io_b_1    (io_weights_0_1_0_0),
    .io_b_2    (io_weights_0_2_0_0),
    .io_result (io_output_0_3_0)
  );
  DotProduct io_output_0_3_1_dot (
    .io_a_0    (io_input_0_3_1),
    .io_a_1    (io_input_1_3_1),
    .io_a_2    (io_input_2_3_1),
    .io_b_0    (io_weights_0_0_0_0),
    .io_b_1    (io_weights_0_1_0_0),
    .io_b_2    (io_weights_0_2_0_0),
    .io_result (io_output_0_3_1)
  );
  DotProduct io_output_0_3_2_dot (
    .io_a_0    (io_input_0_3_2),
    .io_a_1    (io_input_1_3_2),
    .io_a_2    (io_input_2_3_2),
    .io_b_0    (io_weights_0_0_0_0),
    .io_b_1    (io_weights_0_1_0_0),
    .io_b_2    (io_weights_0_2_0_0),
    .io_result (io_output_0_3_2)
  );
  DotProduct io_output_0_3_3_dot (
    .io_a_0    (io_input_0_3_3),
    .io_a_1    (io_input_1_3_3),
    .io_a_2    (io_input_2_3_3),
    .io_b_0    (io_weights_0_0_0_0),
    .io_b_1    (io_weights_0_1_0_0),
    .io_b_2    (io_weights_0_2_0_0),
    .io_result (io_output_0_3_3)
  );
  DotProduct io_output_0_3_4_dot (
    .io_a_0    (io_input_0_3_4),
    .io_a_1    (io_input_1_3_4),
    .io_a_2    (io_input_2_3_4),
    .io_b_0    (io_weights_0_0_0_0),
    .io_b_1    (io_weights_0_1_0_0),
    .io_b_2    (io_weights_0_2_0_0),
    .io_result (io_output_0_3_4)
  );
  DotProduct io_output_0_4_0_dot (
    .io_a_0    (io_input_0_4_0),
    .io_a_1    (io_input_1_4_0),
    .io_a_2    (io_input_2_4_0),
    .io_b_0    (io_weights_0_0_0_0),
    .io_b_1    (io_weights_0_1_0_0),
    .io_b_2    (io_weights_0_2_0_0),
    .io_result (io_output_0_4_0)
  );
  DotProduct io_output_0_4_1_dot (
    .io_a_0    (io_input_0_4_1),
    .io_a_1    (io_input_1_4_1),
    .io_a_2    (io_input_2_4_1),
    .io_b_0    (io_weights_0_0_0_0),
    .io_b_1    (io_weights_0_1_0_0),
    .io_b_2    (io_weights_0_2_0_0),
    .io_result (io_output_0_4_1)
  );
  DotProduct io_output_0_4_2_dot (
    .io_a_0    (io_input_0_4_2),
    .io_a_1    (io_input_1_4_2),
    .io_a_2    (io_input_2_4_2),
    .io_b_0    (io_weights_0_0_0_0),
    .io_b_1    (io_weights_0_1_0_0),
    .io_b_2    (io_weights_0_2_0_0),
    .io_result (io_output_0_4_2)
  );
  DotProduct io_output_0_4_3_dot (
    .io_a_0    (io_input_0_4_3),
    .io_a_1    (io_input_1_4_3),
    .io_a_2    (io_input_2_4_3),
    .io_b_0    (io_weights_0_0_0_0),
    .io_b_1    (io_weights_0_1_0_0),
    .io_b_2    (io_weights_0_2_0_0),
    .io_result (io_output_0_4_3)
  );
  DotProduct io_output_0_4_4_dot (
    .io_a_0    (io_input_0_4_4),
    .io_a_1    (io_input_1_4_4),
    .io_a_2    (io_input_2_4_4),
    .io_b_0    (io_weights_0_0_0_0),
    .io_b_1    (io_weights_0_1_0_0),
    .io_b_2    (io_weights_0_2_0_0),
    .io_result (io_output_0_4_4)
  );
  DotProduct io_output_1_0_0_dot (
    .io_a_0    (io_input_0_0_0),
    .io_a_1    (io_input_1_0_0),
    .io_a_2    (io_input_2_0_0),
    .io_b_0    (io_weights_1_0_0_0),
    .io_b_1    (io_weights_1_1_0_0),
    .io_b_2    (io_weights_1_2_0_0),
    .io_result (io_output_1_0_0)
  );
  DotProduct io_output_1_0_1_dot (
    .io_a_0    (io_input_0_0_1),
    .io_a_1    (io_input_1_0_1),
    .io_a_2    (io_input_2_0_1),
    .io_b_0    (io_weights_1_0_0_0),
    .io_b_1    (io_weights_1_1_0_0),
    .io_b_2    (io_weights_1_2_0_0),
    .io_result (io_output_1_0_1)
  );
  DotProduct io_output_1_0_2_dot (
    .io_a_0    (io_input_0_0_2),
    .io_a_1    (io_input_1_0_2),
    .io_a_2    (io_input_2_0_2),
    .io_b_0    (io_weights_1_0_0_0),
    .io_b_1    (io_weights_1_1_0_0),
    .io_b_2    (io_weights_1_2_0_0),
    .io_result (io_output_1_0_2)
  );
  DotProduct io_output_1_0_3_dot (
    .io_a_0    (io_input_0_0_3),
    .io_a_1    (io_input_1_0_3),
    .io_a_2    (io_input_2_0_3),
    .io_b_0    (io_weights_1_0_0_0),
    .io_b_1    (io_weights_1_1_0_0),
    .io_b_2    (io_weights_1_2_0_0),
    .io_result (io_output_1_0_3)
  );
  DotProduct io_output_1_0_4_dot (
    .io_a_0    (io_input_0_0_4),
    .io_a_1    (io_input_1_0_4),
    .io_a_2    (io_input_2_0_4),
    .io_b_0    (io_weights_1_0_0_0),
    .io_b_1    (io_weights_1_1_0_0),
    .io_b_2    (io_weights_1_2_0_0),
    .io_result (io_output_1_0_4)
  );
  DotProduct io_output_1_1_0_dot (
    .io_a_0    (io_input_0_1_0),
    .io_a_1    (io_input_1_1_0),
    .io_a_2    (io_input_2_1_0),
    .io_b_0    (io_weights_1_0_0_0),
    .io_b_1    (io_weights_1_1_0_0),
    .io_b_2    (io_weights_1_2_0_0),
    .io_result (io_output_1_1_0)
  );
  DotProduct io_output_1_1_1_dot (
    .io_a_0    (io_input_0_1_1),
    .io_a_1    (io_input_1_1_1),
    .io_a_2    (io_input_2_1_1),
    .io_b_0    (io_weights_1_0_0_0),
    .io_b_1    (io_weights_1_1_0_0),
    .io_b_2    (io_weights_1_2_0_0),
    .io_result (io_output_1_1_1)
  );
  DotProduct io_output_1_1_2_dot (
    .io_a_0    (io_input_0_1_2),
    .io_a_1    (io_input_1_1_2),
    .io_a_2    (io_input_2_1_2),
    .io_b_0    (io_weights_1_0_0_0),
    .io_b_1    (io_weights_1_1_0_0),
    .io_b_2    (io_weights_1_2_0_0),
    .io_result (io_output_1_1_2)
  );
  DotProduct io_output_1_1_3_dot (
    .io_a_0    (io_input_0_1_3),
    .io_a_1    (io_input_1_1_3),
    .io_a_2    (io_input_2_1_3),
    .io_b_0    (io_weights_1_0_0_0),
    .io_b_1    (io_weights_1_1_0_0),
    .io_b_2    (io_weights_1_2_0_0),
    .io_result (io_output_1_1_3)
  );
  DotProduct io_output_1_1_4_dot (
    .io_a_0    (io_input_0_1_4),
    .io_a_1    (io_input_1_1_4),
    .io_a_2    (io_input_2_1_4),
    .io_b_0    (io_weights_1_0_0_0),
    .io_b_1    (io_weights_1_1_0_0),
    .io_b_2    (io_weights_1_2_0_0),
    .io_result (io_output_1_1_4)
  );
  DotProduct io_output_1_2_0_dot (
    .io_a_0    (io_input_0_2_0),
    .io_a_1    (io_input_1_2_0),
    .io_a_2    (io_input_2_2_0),
    .io_b_0    (io_weights_1_0_0_0),
    .io_b_1    (io_weights_1_1_0_0),
    .io_b_2    (io_weights_1_2_0_0),
    .io_result (io_output_1_2_0)
  );
  DotProduct io_output_1_2_1_dot (
    .io_a_0    (io_input_0_2_1),
    .io_a_1    (io_input_1_2_1),
    .io_a_2    (io_input_2_2_1),
    .io_b_0    (io_weights_1_0_0_0),
    .io_b_1    (io_weights_1_1_0_0),
    .io_b_2    (io_weights_1_2_0_0),
    .io_result (io_output_1_2_1)
  );
  DotProduct io_output_1_2_2_dot (
    .io_a_0    (io_input_0_2_2),
    .io_a_1    (io_input_1_2_2),
    .io_a_2    (io_input_2_2_2),
    .io_b_0    (io_weights_1_0_0_0),
    .io_b_1    (io_weights_1_1_0_0),
    .io_b_2    (io_weights_1_2_0_0),
    .io_result (io_output_1_2_2)
  );
  DotProduct io_output_1_2_3_dot (
    .io_a_0    (io_input_0_2_3),
    .io_a_1    (io_input_1_2_3),
    .io_a_2    (io_input_2_2_3),
    .io_b_0    (io_weights_1_0_0_0),
    .io_b_1    (io_weights_1_1_0_0),
    .io_b_2    (io_weights_1_2_0_0),
    .io_result (io_output_1_2_3)
  );
  DotProduct io_output_1_2_4_dot (
    .io_a_0    (io_input_0_2_4),
    .io_a_1    (io_input_1_2_4),
    .io_a_2    (io_input_2_2_4),
    .io_b_0    (io_weights_1_0_0_0),
    .io_b_1    (io_weights_1_1_0_0),
    .io_b_2    (io_weights_1_2_0_0),
    .io_result (io_output_1_2_4)
  );
  DotProduct io_output_1_3_0_dot (
    .io_a_0    (io_input_0_3_0),
    .io_a_1    (io_input_1_3_0),
    .io_a_2    (io_input_2_3_0),
    .io_b_0    (io_weights_1_0_0_0),
    .io_b_1    (io_weights_1_1_0_0),
    .io_b_2    (io_weights_1_2_0_0),
    .io_result (io_output_1_3_0)
  );
  DotProduct io_output_1_3_1_dot (
    .io_a_0    (io_input_0_3_1),
    .io_a_1    (io_input_1_3_1),
    .io_a_2    (io_input_2_3_1),
    .io_b_0    (io_weights_1_0_0_0),
    .io_b_1    (io_weights_1_1_0_0),
    .io_b_2    (io_weights_1_2_0_0),
    .io_result (io_output_1_3_1)
  );
  DotProduct io_output_1_3_2_dot (
    .io_a_0    (io_input_0_3_2),
    .io_a_1    (io_input_1_3_2),
    .io_a_2    (io_input_2_3_2),
    .io_b_0    (io_weights_1_0_0_0),
    .io_b_1    (io_weights_1_1_0_0),
    .io_b_2    (io_weights_1_2_0_0),
    .io_result (io_output_1_3_2)
  );
  DotProduct io_output_1_3_3_dot (
    .io_a_0    (io_input_0_3_3),
    .io_a_1    (io_input_1_3_3),
    .io_a_2    (io_input_2_3_3),
    .io_b_0    (io_weights_1_0_0_0),
    .io_b_1    (io_weights_1_1_0_0),
    .io_b_2    (io_weights_1_2_0_0),
    .io_result (io_output_1_3_3)
  );
  DotProduct io_output_1_3_4_dot (
    .io_a_0    (io_input_0_3_4),
    .io_a_1    (io_input_1_3_4),
    .io_a_2    (io_input_2_3_4),
    .io_b_0    (io_weights_1_0_0_0),
    .io_b_1    (io_weights_1_1_0_0),
    .io_b_2    (io_weights_1_2_0_0),
    .io_result (io_output_1_3_4)
  );
  DotProduct io_output_1_4_0_dot (
    .io_a_0    (io_input_0_4_0),
    .io_a_1    (io_input_1_4_0),
    .io_a_2    (io_input_2_4_0),
    .io_b_0    (io_weights_1_0_0_0),
    .io_b_1    (io_weights_1_1_0_0),
    .io_b_2    (io_weights_1_2_0_0),
    .io_result (io_output_1_4_0)
  );
  DotProduct io_output_1_4_1_dot (
    .io_a_0    (io_input_0_4_1),
    .io_a_1    (io_input_1_4_1),
    .io_a_2    (io_input_2_4_1),
    .io_b_0    (io_weights_1_0_0_0),
    .io_b_1    (io_weights_1_1_0_0),
    .io_b_2    (io_weights_1_2_0_0),
    .io_result (io_output_1_4_1)
  );
  DotProduct io_output_1_4_2_dot (
    .io_a_0    (io_input_0_4_2),
    .io_a_1    (io_input_1_4_2),
    .io_a_2    (io_input_2_4_2),
    .io_b_0    (io_weights_1_0_0_0),
    .io_b_1    (io_weights_1_1_0_0),
    .io_b_2    (io_weights_1_2_0_0),
    .io_result (io_output_1_4_2)
  );
  DotProduct io_output_1_4_3_dot (
    .io_a_0    (io_input_0_4_3),
    .io_a_1    (io_input_1_4_3),
    .io_a_2    (io_input_2_4_3),
    .io_b_0    (io_weights_1_0_0_0),
    .io_b_1    (io_weights_1_1_0_0),
    .io_b_2    (io_weights_1_2_0_0),
    .io_result (io_output_1_4_3)
  );
  DotProduct io_output_1_4_4_dot (
    .io_a_0    (io_input_0_4_4),
    .io_a_1    (io_input_1_4_4),
    .io_a_2    (io_input_2_4_4),
    .io_b_0    (io_weights_1_0_0_0),
    .io_b_1    (io_weights_1_1_0_0),
    .io_b_2    (io_weights_1_2_0_0),
    .io_result (io_output_1_4_4)
  );
  DotProduct io_output_2_0_0_dot (
    .io_a_0    (io_input_0_0_0),
    .io_a_1    (io_input_1_0_0),
    .io_a_2    (io_input_2_0_0),
    .io_b_0    (io_weights_2_0_0_0),
    .io_b_1    (io_weights_2_1_0_0),
    .io_b_2    (io_weights_2_2_0_0),
    .io_result (io_output_2_0_0)
  );
  DotProduct io_output_2_0_1_dot (
    .io_a_0    (io_input_0_0_1),
    .io_a_1    (io_input_1_0_1),
    .io_a_2    (io_input_2_0_1),
    .io_b_0    (io_weights_2_0_0_0),
    .io_b_1    (io_weights_2_1_0_0),
    .io_b_2    (io_weights_2_2_0_0),
    .io_result (io_output_2_0_1)
  );
  DotProduct io_output_2_0_2_dot (
    .io_a_0    (io_input_0_0_2),
    .io_a_1    (io_input_1_0_2),
    .io_a_2    (io_input_2_0_2),
    .io_b_0    (io_weights_2_0_0_0),
    .io_b_1    (io_weights_2_1_0_0),
    .io_b_2    (io_weights_2_2_0_0),
    .io_result (io_output_2_0_2)
  );
  DotProduct io_output_2_0_3_dot (
    .io_a_0    (io_input_0_0_3),
    .io_a_1    (io_input_1_0_3),
    .io_a_2    (io_input_2_0_3),
    .io_b_0    (io_weights_2_0_0_0),
    .io_b_1    (io_weights_2_1_0_0),
    .io_b_2    (io_weights_2_2_0_0),
    .io_result (io_output_2_0_3)
  );
  DotProduct io_output_2_0_4_dot (
    .io_a_0    (io_input_0_0_4),
    .io_a_1    (io_input_1_0_4),
    .io_a_2    (io_input_2_0_4),
    .io_b_0    (io_weights_2_0_0_0),
    .io_b_1    (io_weights_2_1_0_0),
    .io_b_2    (io_weights_2_2_0_0),
    .io_result (io_output_2_0_4)
  );
  DotProduct io_output_2_1_0_dot (
    .io_a_0    (io_input_0_1_0),
    .io_a_1    (io_input_1_1_0),
    .io_a_2    (io_input_2_1_0),
    .io_b_0    (io_weights_2_0_0_0),
    .io_b_1    (io_weights_2_1_0_0),
    .io_b_2    (io_weights_2_2_0_0),
    .io_result (io_output_2_1_0)
  );
  DotProduct io_output_2_1_1_dot (
    .io_a_0    (io_input_0_1_1),
    .io_a_1    (io_input_1_1_1),
    .io_a_2    (io_input_2_1_1),
    .io_b_0    (io_weights_2_0_0_0),
    .io_b_1    (io_weights_2_1_0_0),
    .io_b_2    (io_weights_2_2_0_0),
    .io_result (io_output_2_1_1)
  );
  DotProduct io_output_2_1_2_dot (
    .io_a_0    (io_input_0_1_2),
    .io_a_1    (io_input_1_1_2),
    .io_a_2    (io_input_2_1_2),
    .io_b_0    (io_weights_2_0_0_0),
    .io_b_1    (io_weights_2_1_0_0),
    .io_b_2    (io_weights_2_2_0_0),
    .io_result (io_output_2_1_2)
  );
  DotProduct io_output_2_1_3_dot (
    .io_a_0    (io_input_0_1_3),
    .io_a_1    (io_input_1_1_3),
    .io_a_2    (io_input_2_1_3),
    .io_b_0    (io_weights_2_0_0_0),
    .io_b_1    (io_weights_2_1_0_0),
    .io_b_2    (io_weights_2_2_0_0),
    .io_result (io_output_2_1_3)
  );
  DotProduct io_output_2_1_4_dot (
    .io_a_0    (io_input_0_1_4),
    .io_a_1    (io_input_1_1_4),
    .io_a_2    (io_input_2_1_4),
    .io_b_0    (io_weights_2_0_0_0),
    .io_b_1    (io_weights_2_1_0_0),
    .io_b_2    (io_weights_2_2_0_0),
    .io_result (io_output_2_1_4)
  );
  DotProduct io_output_2_2_0_dot (
    .io_a_0    (io_input_0_2_0),
    .io_a_1    (io_input_1_2_0),
    .io_a_2    (io_input_2_2_0),
    .io_b_0    (io_weights_2_0_0_0),
    .io_b_1    (io_weights_2_1_0_0),
    .io_b_2    (io_weights_2_2_0_0),
    .io_result (io_output_2_2_0)
  );
  DotProduct io_output_2_2_1_dot (
    .io_a_0    (io_input_0_2_1),
    .io_a_1    (io_input_1_2_1),
    .io_a_2    (io_input_2_2_1),
    .io_b_0    (io_weights_2_0_0_0),
    .io_b_1    (io_weights_2_1_0_0),
    .io_b_2    (io_weights_2_2_0_0),
    .io_result (io_output_2_2_1)
  );
  DotProduct io_output_2_2_2_dot (
    .io_a_0    (io_input_0_2_2),
    .io_a_1    (io_input_1_2_2),
    .io_a_2    (io_input_2_2_2),
    .io_b_0    (io_weights_2_0_0_0),
    .io_b_1    (io_weights_2_1_0_0),
    .io_b_2    (io_weights_2_2_0_0),
    .io_result (io_output_2_2_2)
  );
  DotProduct io_output_2_2_3_dot (
    .io_a_0    (io_input_0_2_3),
    .io_a_1    (io_input_1_2_3),
    .io_a_2    (io_input_2_2_3),
    .io_b_0    (io_weights_2_0_0_0),
    .io_b_1    (io_weights_2_1_0_0),
    .io_b_2    (io_weights_2_2_0_0),
    .io_result (io_output_2_2_3)
  );
  DotProduct io_output_2_2_4_dot (
    .io_a_0    (io_input_0_2_4),
    .io_a_1    (io_input_1_2_4),
    .io_a_2    (io_input_2_2_4),
    .io_b_0    (io_weights_2_0_0_0),
    .io_b_1    (io_weights_2_1_0_0),
    .io_b_2    (io_weights_2_2_0_0),
    .io_result (io_output_2_2_4)
  );
  DotProduct io_output_2_3_0_dot (
    .io_a_0    (io_input_0_3_0),
    .io_a_1    (io_input_1_3_0),
    .io_a_2    (io_input_2_3_0),
    .io_b_0    (io_weights_2_0_0_0),
    .io_b_1    (io_weights_2_1_0_0),
    .io_b_2    (io_weights_2_2_0_0),
    .io_result (io_output_2_3_0)
  );
  DotProduct io_output_2_3_1_dot (
    .io_a_0    (io_input_0_3_1),
    .io_a_1    (io_input_1_3_1),
    .io_a_2    (io_input_2_3_1),
    .io_b_0    (io_weights_2_0_0_0),
    .io_b_1    (io_weights_2_1_0_0),
    .io_b_2    (io_weights_2_2_0_0),
    .io_result (io_output_2_3_1)
  );
  DotProduct io_output_2_3_2_dot (
    .io_a_0    (io_input_0_3_2),
    .io_a_1    (io_input_1_3_2),
    .io_a_2    (io_input_2_3_2),
    .io_b_0    (io_weights_2_0_0_0),
    .io_b_1    (io_weights_2_1_0_0),
    .io_b_2    (io_weights_2_2_0_0),
    .io_result (io_output_2_3_2)
  );
  DotProduct io_output_2_3_3_dot (
    .io_a_0    (io_input_0_3_3),
    .io_a_1    (io_input_1_3_3),
    .io_a_2    (io_input_2_3_3),
    .io_b_0    (io_weights_2_0_0_0),
    .io_b_1    (io_weights_2_1_0_0),
    .io_b_2    (io_weights_2_2_0_0),
    .io_result (io_output_2_3_3)
  );
  DotProduct io_output_2_3_4_dot (
    .io_a_0    (io_input_0_3_4),
    .io_a_1    (io_input_1_3_4),
    .io_a_2    (io_input_2_3_4),
    .io_b_0    (io_weights_2_0_0_0),
    .io_b_1    (io_weights_2_1_0_0),
    .io_b_2    (io_weights_2_2_0_0),
    .io_result (io_output_2_3_4)
  );
  DotProduct io_output_2_4_0_dot (
    .io_a_0    (io_input_0_4_0),
    .io_a_1    (io_input_1_4_0),
    .io_a_2    (io_input_2_4_0),
    .io_b_0    (io_weights_2_0_0_0),
    .io_b_1    (io_weights_2_1_0_0),
    .io_b_2    (io_weights_2_2_0_0),
    .io_result (io_output_2_4_0)
  );
  DotProduct io_output_2_4_1_dot (
    .io_a_0    (io_input_0_4_1),
    .io_a_1    (io_input_1_4_1),
    .io_a_2    (io_input_2_4_1),
    .io_b_0    (io_weights_2_0_0_0),
    .io_b_1    (io_weights_2_1_0_0),
    .io_b_2    (io_weights_2_2_0_0),
    .io_result (io_output_2_4_1)
  );
  DotProduct io_output_2_4_2_dot (
    .io_a_0    (io_input_0_4_2),
    .io_a_1    (io_input_1_4_2),
    .io_a_2    (io_input_2_4_2),
    .io_b_0    (io_weights_2_0_0_0),
    .io_b_1    (io_weights_2_1_0_0),
    .io_b_2    (io_weights_2_2_0_0),
    .io_result (io_output_2_4_2)
  );
  DotProduct io_output_2_4_3_dot (
    .io_a_0    (io_input_0_4_3),
    .io_a_1    (io_input_1_4_3),
    .io_a_2    (io_input_2_4_3),
    .io_b_0    (io_weights_2_0_0_0),
    .io_b_1    (io_weights_2_1_0_0),
    .io_b_2    (io_weights_2_2_0_0),
    .io_result (io_output_2_4_3)
  );
  DotProduct io_output_2_4_4_dot (
    .io_a_0    (io_input_0_4_4),
    .io_a_1    (io_input_1_4_4),
    .io_a_2    (io_input_2_4_4),
    .io_b_0    (io_weights_2_0_0_0),
    .io_b_1    (io_weights_2_1_0_0),
    .io_b_2    (io_weights_2_2_0_0),
    .io_result (io_output_2_4_4)
  );
  DotProduct io_output_3_0_0_dot (
    .io_a_0    (io_input_0_0_0),
    .io_a_1    (io_input_1_0_0),
    .io_a_2    (io_input_2_0_0),
    .io_b_0    (io_weights_3_0_0_0),
    .io_b_1    (io_weights_3_1_0_0),
    .io_b_2    (io_weights_3_2_0_0),
    .io_result (io_output_3_0_0)
  );
  DotProduct io_output_3_0_1_dot (
    .io_a_0    (io_input_0_0_1),
    .io_a_1    (io_input_1_0_1),
    .io_a_2    (io_input_2_0_1),
    .io_b_0    (io_weights_3_0_0_0),
    .io_b_1    (io_weights_3_1_0_0),
    .io_b_2    (io_weights_3_2_0_0),
    .io_result (io_output_3_0_1)
  );
  DotProduct io_output_3_0_2_dot (
    .io_a_0    (io_input_0_0_2),
    .io_a_1    (io_input_1_0_2),
    .io_a_2    (io_input_2_0_2),
    .io_b_0    (io_weights_3_0_0_0),
    .io_b_1    (io_weights_3_1_0_0),
    .io_b_2    (io_weights_3_2_0_0),
    .io_result (io_output_3_0_2)
  );
  DotProduct io_output_3_0_3_dot (
    .io_a_0    (io_input_0_0_3),
    .io_a_1    (io_input_1_0_3),
    .io_a_2    (io_input_2_0_3),
    .io_b_0    (io_weights_3_0_0_0),
    .io_b_1    (io_weights_3_1_0_0),
    .io_b_2    (io_weights_3_2_0_0),
    .io_result (io_output_3_0_3)
  );
  DotProduct io_output_3_0_4_dot (
    .io_a_0    (io_input_0_0_4),
    .io_a_1    (io_input_1_0_4),
    .io_a_2    (io_input_2_0_4),
    .io_b_0    (io_weights_3_0_0_0),
    .io_b_1    (io_weights_3_1_0_0),
    .io_b_2    (io_weights_3_2_0_0),
    .io_result (io_output_3_0_4)
  );
  DotProduct io_output_3_1_0_dot (
    .io_a_0    (io_input_0_1_0),
    .io_a_1    (io_input_1_1_0),
    .io_a_2    (io_input_2_1_0),
    .io_b_0    (io_weights_3_0_0_0),
    .io_b_1    (io_weights_3_1_0_0),
    .io_b_2    (io_weights_3_2_0_0),
    .io_result (io_output_3_1_0)
  );
  DotProduct io_output_3_1_1_dot (
    .io_a_0    (io_input_0_1_1),
    .io_a_1    (io_input_1_1_1),
    .io_a_2    (io_input_2_1_1),
    .io_b_0    (io_weights_3_0_0_0),
    .io_b_1    (io_weights_3_1_0_0),
    .io_b_2    (io_weights_3_2_0_0),
    .io_result (io_output_3_1_1)
  );
  DotProduct io_output_3_1_2_dot (
    .io_a_0    (io_input_0_1_2),
    .io_a_1    (io_input_1_1_2),
    .io_a_2    (io_input_2_1_2),
    .io_b_0    (io_weights_3_0_0_0),
    .io_b_1    (io_weights_3_1_0_0),
    .io_b_2    (io_weights_3_2_0_0),
    .io_result (io_output_3_1_2)
  );
  DotProduct io_output_3_1_3_dot (
    .io_a_0    (io_input_0_1_3),
    .io_a_1    (io_input_1_1_3),
    .io_a_2    (io_input_2_1_3),
    .io_b_0    (io_weights_3_0_0_0),
    .io_b_1    (io_weights_3_1_0_0),
    .io_b_2    (io_weights_3_2_0_0),
    .io_result (io_output_3_1_3)
  );
  DotProduct io_output_3_1_4_dot (
    .io_a_0    (io_input_0_1_4),
    .io_a_1    (io_input_1_1_4),
    .io_a_2    (io_input_2_1_4),
    .io_b_0    (io_weights_3_0_0_0),
    .io_b_1    (io_weights_3_1_0_0),
    .io_b_2    (io_weights_3_2_0_0),
    .io_result (io_output_3_1_4)
  );
  DotProduct io_output_3_2_0_dot (
    .io_a_0    (io_input_0_2_0),
    .io_a_1    (io_input_1_2_0),
    .io_a_2    (io_input_2_2_0),
    .io_b_0    (io_weights_3_0_0_0),
    .io_b_1    (io_weights_3_1_0_0),
    .io_b_2    (io_weights_3_2_0_0),
    .io_result (io_output_3_2_0)
  );
  DotProduct io_output_3_2_1_dot (
    .io_a_0    (io_input_0_2_1),
    .io_a_1    (io_input_1_2_1),
    .io_a_2    (io_input_2_2_1),
    .io_b_0    (io_weights_3_0_0_0),
    .io_b_1    (io_weights_3_1_0_0),
    .io_b_2    (io_weights_3_2_0_0),
    .io_result (io_output_3_2_1)
  );
  DotProduct io_output_3_2_2_dot (
    .io_a_0    (io_input_0_2_2),
    .io_a_1    (io_input_1_2_2),
    .io_a_2    (io_input_2_2_2),
    .io_b_0    (io_weights_3_0_0_0),
    .io_b_1    (io_weights_3_1_0_0),
    .io_b_2    (io_weights_3_2_0_0),
    .io_result (io_output_3_2_2)
  );
  DotProduct io_output_3_2_3_dot (
    .io_a_0    (io_input_0_2_3),
    .io_a_1    (io_input_1_2_3),
    .io_a_2    (io_input_2_2_3),
    .io_b_0    (io_weights_3_0_0_0),
    .io_b_1    (io_weights_3_1_0_0),
    .io_b_2    (io_weights_3_2_0_0),
    .io_result (io_output_3_2_3)
  );
  DotProduct io_output_3_2_4_dot (
    .io_a_0    (io_input_0_2_4),
    .io_a_1    (io_input_1_2_4),
    .io_a_2    (io_input_2_2_4),
    .io_b_0    (io_weights_3_0_0_0),
    .io_b_1    (io_weights_3_1_0_0),
    .io_b_2    (io_weights_3_2_0_0),
    .io_result (io_output_3_2_4)
  );
  DotProduct io_output_3_3_0_dot (
    .io_a_0    (io_input_0_3_0),
    .io_a_1    (io_input_1_3_0),
    .io_a_2    (io_input_2_3_0),
    .io_b_0    (io_weights_3_0_0_0),
    .io_b_1    (io_weights_3_1_0_0),
    .io_b_2    (io_weights_3_2_0_0),
    .io_result (io_output_3_3_0)
  );
  DotProduct io_output_3_3_1_dot (
    .io_a_0    (io_input_0_3_1),
    .io_a_1    (io_input_1_3_1),
    .io_a_2    (io_input_2_3_1),
    .io_b_0    (io_weights_3_0_0_0),
    .io_b_1    (io_weights_3_1_0_0),
    .io_b_2    (io_weights_3_2_0_0),
    .io_result (io_output_3_3_1)
  );
  DotProduct io_output_3_3_2_dot (
    .io_a_0    (io_input_0_3_2),
    .io_a_1    (io_input_1_3_2),
    .io_a_2    (io_input_2_3_2),
    .io_b_0    (io_weights_3_0_0_0),
    .io_b_1    (io_weights_3_1_0_0),
    .io_b_2    (io_weights_3_2_0_0),
    .io_result (io_output_3_3_2)
  );
  DotProduct io_output_3_3_3_dot (
    .io_a_0    (io_input_0_3_3),
    .io_a_1    (io_input_1_3_3),
    .io_a_2    (io_input_2_3_3),
    .io_b_0    (io_weights_3_0_0_0),
    .io_b_1    (io_weights_3_1_0_0),
    .io_b_2    (io_weights_3_2_0_0),
    .io_result (io_output_3_3_3)
  );
  DotProduct io_output_3_3_4_dot (
    .io_a_0    (io_input_0_3_4),
    .io_a_1    (io_input_1_3_4),
    .io_a_2    (io_input_2_3_4),
    .io_b_0    (io_weights_3_0_0_0),
    .io_b_1    (io_weights_3_1_0_0),
    .io_b_2    (io_weights_3_2_0_0),
    .io_result (io_output_3_3_4)
  );
  DotProduct io_output_3_4_0_dot (
    .io_a_0    (io_input_0_4_0),
    .io_a_1    (io_input_1_4_0),
    .io_a_2    (io_input_2_4_0),
    .io_b_0    (io_weights_3_0_0_0),
    .io_b_1    (io_weights_3_1_0_0),
    .io_b_2    (io_weights_3_2_0_0),
    .io_result (io_output_3_4_0)
  );
  DotProduct io_output_3_4_1_dot (
    .io_a_0    (io_input_0_4_1),
    .io_a_1    (io_input_1_4_1),
    .io_a_2    (io_input_2_4_1),
    .io_b_0    (io_weights_3_0_0_0),
    .io_b_1    (io_weights_3_1_0_0),
    .io_b_2    (io_weights_3_2_0_0),
    .io_result (io_output_3_4_1)
  );
  DotProduct io_output_3_4_2_dot (
    .io_a_0    (io_input_0_4_2),
    .io_a_1    (io_input_1_4_2),
    .io_a_2    (io_input_2_4_2),
    .io_b_0    (io_weights_3_0_0_0),
    .io_b_1    (io_weights_3_1_0_0),
    .io_b_2    (io_weights_3_2_0_0),
    .io_result (io_output_3_4_2)
  );
  DotProduct io_output_3_4_3_dot (
    .io_a_0    (io_input_0_4_3),
    .io_a_1    (io_input_1_4_3),
    .io_a_2    (io_input_2_4_3),
    .io_b_0    (io_weights_3_0_0_0),
    .io_b_1    (io_weights_3_1_0_0),
    .io_b_2    (io_weights_3_2_0_0),
    .io_result (io_output_3_4_3)
  );
  DotProduct io_output_3_4_4_dot (
    .io_a_0    (io_input_0_4_4),
    .io_a_1    (io_input_1_4_4),
    .io_a_2    (io_input_2_4_4),
    .io_b_0    (io_weights_3_0_0_0),
    .io_b_1    (io_weights_3_1_0_0),
    .io_b_2    (io_weights_3_2_0_0),
    .io_result (io_output_3_4_4)
  );
endmodule

