
#include <verilated.h>
#include <verilated_vcd_c.h>
#include <fstream>
#include <iostream>
#include <sstream>
#include <vector>
#include <string>
#include "VRegularConvFull_SA_Tiled.h"

static std::vector<long long> read_ints(const std::string &path) {
  std::ifstream ifs(path);
  if (!ifs) throw std::runtime_error("cannot open: " + path);
  std::vector<long long> v;
  std::string line;
  while (std::getline(ifs, line)) {
    auto p = line.find('#');
    if (p != std::string::npos) line = line.substr(0, p);
    std::stringstream ss(line);
    long long x;
    if (ss >> x) v.push_back(x);
  }
  return v;
}

static void write_ints(const std::string &path, const std::vector<long long> &v) {
  std::ofstream ofs(path);
  if (!ofs) throw std::runtime_error("cannot write: " + path);
  for (auto x : v) ofs << x << "\n";
}

int main(int argc, char** argv) {
  Verilated::commandArgs(argc, argv);

  const std::string dir = "../tests/vectors_sa_tiled/case12";
  const auto meta = read_ints(dir + "/meta.txt");
  if (meta.size() < 7) {
    std::cerr << "meta.txt must have 7 lines\n";
    return 1;
  }

  const auto inVec = read_ints(dir + "/input.txt");
  const auto wVec  = read_ints(dir + "/weight.txt");

  auto* dut = new VRegularConvFull_SA_Tiled;

  Verilated::traceEverOn(true);
  auto* tfp = new VerilatedVcdC;
  dut->trace(tfp, 99);
  tfp->open("wave_case12.vcd");

  vluint64_t t = 0;
  auto tick = [&]() {
    dut->clock = 0; dut->eval(); tfp->dump(t++);
    dut->clock = 1; dut->eval(); tfp->dump(t++);
  };

  dut->reset = 1;
  dut->io_start = 0;
  for (int i = 0; i < 5; i++) tick();
  dut->reset = 0;
  for (int i = 0; i < 2; i++) tick();

  if ((int)inVec.size() != (int)64) {
    std::cerr << "input length mismatch vs pin count: " << inVec.size() << " vs " << 64 << "\n";
    return 1;
  }
  dut->io_x_in_0_0 = (int)inVec[0];
  dut->io_x_in_0_1 = (int)inVec[1];
  dut->io_x_in_0_2 = (int)inVec[2];
  dut->io_x_in_0_3 = (int)inVec[3];
  dut->io_x_in_0_4 = (int)inVec[4];
  dut->io_x_in_0_5 = (int)inVec[5];
  dut->io_x_in_0_6 = (int)inVec[6];
  dut->io_x_in_0_7 = (int)inVec[7];
  dut->io_x_in_0_8 = (int)inVec[8];
  dut->io_x_in_0_9 = (int)inVec[9];
  dut->io_x_in_0_10 = (int)inVec[10];
  dut->io_x_in_0_11 = (int)inVec[11];
  dut->io_x_in_0_12 = (int)inVec[12];
  dut->io_x_in_0_13 = (int)inVec[13];
  dut->io_x_in_0_14 = (int)inVec[14];
  dut->io_x_in_0_15 = (int)inVec[15];
  dut->io_x_in_0_16 = (int)inVec[16];
  dut->io_x_in_0_17 = (int)inVec[17];
  dut->io_x_in_0_18 = (int)inVec[18];
  dut->io_x_in_0_19 = (int)inVec[19];
  dut->io_x_in_0_20 = (int)inVec[20];
  dut->io_x_in_0_21 = (int)inVec[21];
  dut->io_x_in_0_22 = (int)inVec[22];
  dut->io_x_in_0_23 = (int)inVec[23];
  dut->io_x_in_0_24 = (int)inVec[24];
  dut->io_x_in_0_25 = (int)inVec[25];
  dut->io_x_in_0_26 = (int)inVec[26];
  dut->io_x_in_0_27 = (int)inVec[27];
  dut->io_x_in_0_28 = (int)inVec[28];
  dut->io_x_in_0_29 = (int)inVec[29];
  dut->io_x_in_0_30 = (int)inVec[30];
  dut->io_x_in_0_31 = (int)inVec[31];
  dut->io_x_in_0_32 = (int)inVec[32];
  dut->io_x_in_0_33 = (int)inVec[33];
  dut->io_x_in_0_34 = (int)inVec[34];
  dut->io_x_in_0_35 = (int)inVec[35];
  dut->io_x_in_0_36 = (int)inVec[36];
  dut->io_x_in_0_37 = (int)inVec[37];
  dut->io_x_in_0_38 = (int)inVec[38];
  dut->io_x_in_0_39 = (int)inVec[39];
  dut->io_x_in_0_40 = (int)inVec[40];
  dut->io_x_in_0_41 = (int)inVec[41];
  dut->io_x_in_0_42 = (int)inVec[42];
  dut->io_x_in_0_43 = (int)inVec[43];
  dut->io_x_in_0_44 = (int)inVec[44];
  dut->io_x_in_0_45 = (int)inVec[45];
  dut->io_x_in_0_46 = (int)inVec[46];
  dut->io_x_in_0_47 = (int)inVec[47];
  dut->io_x_in_0_48 = (int)inVec[48];
  dut->io_x_in_0_49 = (int)inVec[49];
  dut->io_x_in_0_50 = (int)inVec[50];
  dut->io_x_in_0_51 = (int)inVec[51];
  dut->io_x_in_0_52 = (int)inVec[52];
  dut->io_x_in_0_53 = (int)inVec[53];
  dut->io_x_in_0_54 = (int)inVec[54];
  dut->io_x_in_0_55 = (int)inVec[55];
  dut->io_x_in_0_56 = (int)inVec[56];
  dut->io_x_in_0_57 = (int)inVec[57];
  dut->io_x_in_0_58 = (int)inVec[58];
  dut->io_x_in_0_59 = (int)inVec[59];
  dut->io_x_in_0_60 = (int)inVec[60];
  dut->io_x_in_0_61 = (int)inVec[61];
  dut->io_x_in_0_62 = (int)inVec[62];
  dut->io_x_in_0_63 = (int)inVec[63];

  if ((int)wVec.size() != (int)72) {
    std::cerr << "weight length mismatch vs pin count: " << wVec.size() << " vs " << 72 << "\n";
    return 1;
  }
  dut->io_w_in_0_0 = (int)wVec[0];
  dut->io_w_in_0_1 = (int)wVec[1];
  dut->io_w_in_0_2 = (int)wVec[2];
  dut->io_w_in_0_3 = (int)wVec[3];
  dut->io_w_in_0_4 = (int)wVec[4];
  dut->io_w_in_0_5 = (int)wVec[5];
  dut->io_w_in_0_6 = (int)wVec[6];
  dut->io_w_in_0_7 = (int)wVec[7];
  dut->io_w_in_0_8 = (int)wVec[8];
  dut->io_w_in_1_0 = (int)wVec[9];
  dut->io_w_in_1_1 = (int)wVec[10];
  dut->io_w_in_1_2 = (int)wVec[11];
  dut->io_w_in_1_3 = (int)wVec[12];
  dut->io_w_in_1_4 = (int)wVec[13];
  dut->io_w_in_1_5 = (int)wVec[14];
  dut->io_w_in_1_6 = (int)wVec[15];
  dut->io_w_in_1_7 = (int)wVec[16];
  dut->io_w_in_1_8 = (int)wVec[17];
  dut->io_w_in_2_0 = (int)wVec[18];
  dut->io_w_in_2_1 = (int)wVec[19];
  dut->io_w_in_2_2 = (int)wVec[20];
  dut->io_w_in_2_3 = (int)wVec[21];
  dut->io_w_in_2_4 = (int)wVec[22];
  dut->io_w_in_2_5 = (int)wVec[23];
  dut->io_w_in_2_6 = (int)wVec[24];
  dut->io_w_in_2_7 = (int)wVec[25];
  dut->io_w_in_2_8 = (int)wVec[26];
  dut->io_w_in_3_0 = (int)wVec[27];
  dut->io_w_in_3_1 = (int)wVec[28];
  dut->io_w_in_3_2 = (int)wVec[29];
  dut->io_w_in_3_3 = (int)wVec[30];
  dut->io_w_in_3_4 = (int)wVec[31];
  dut->io_w_in_3_5 = (int)wVec[32];
  dut->io_w_in_3_6 = (int)wVec[33];
  dut->io_w_in_3_7 = (int)wVec[34];
  dut->io_w_in_3_8 = (int)wVec[35];
  dut->io_w_in_4_0 = (int)wVec[36];
  dut->io_w_in_4_1 = (int)wVec[37];
  dut->io_w_in_4_2 = (int)wVec[38];
  dut->io_w_in_4_3 = (int)wVec[39];
  dut->io_w_in_4_4 = (int)wVec[40];
  dut->io_w_in_4_5 = (int)wVec[41];
  dut->io_w_in_4_6 = (int)wVec[42];
  dut->io_w_in_4_7 = (int)wVec[43];
  dut->io_w_in_4_8 = (int)wVec[44];
  dut->io_w_in_5_0 = (int)wVec[45];
  dut->io_w_in_5_1 = (int)wVec[46];
  dut->io_w_in_5_2 = (int)wVec[47];
  dut->io_w_in_5_3 = (int)wVec[48];
  dut->io_w_in_5_4 = (int)wVec[49];
  dut->io_w_in_5_5 = (int)wVec[50];
  dut->io_w_in_5_6 = (int)wVec[51];
  dut->io_w_in_5_7 = (int)wVec[52];
  dut->io_w_in_5_8 = (int)wVec[53];
  dut->io_w_in_6_0 = (int)wVec[54];
  dut->io_w_in_6_1 = (int)wVec[55];
  dut->io_w_in_6_2 = (int)wVec[56];
  dut->io_w_in_6_3 = (int)wVec[57];
  dut->io_w_in_6_4 = (int)wVec[58];
  dut->io_w_in_6_5 = (int)wVec[59];
  dut->io_w_in_6_6 = (int)wVec[60];
  dut->io_w_in_6_7 = (int)wVec[61];
  dut->io_w_in_6_8 = (int)wVec[62];
  dut->io_w_in_7_0 = (int)wVec[63];
  dut->io_w_in_7_1 = (int)wVec[64];
  dut->io_w_in_7_2 = (int)wVec[65];
  dut->io_w_in_7_3 = (int)wVec[66];
  dut->io_w_in_7_4 = (int)wVec[67];
  dut->io_w_in_7_5 = (int)wVec[68];
  dut->io_w_in_7_6 = (int)wVec[69];
  dut->io_w_in_7_7 = (int)wVec[70];
  dut->io_w_in_7_8 = (int)wVec[71];

  dut->io_start = 1;
  tick();
  dut->io_start = 0;

  const int maxCycles = 300000;
  int cyc = 0;
  while (!dut->io_done) {
    tick();
    cyc++;
    if (cyc > maxCycles) {
      std::cerr << "TIMEOUT\n";
      return 1;
    }
  }

  std::vector<long long> observed;
  observed.reserve(288);
  observed.push_back((int32_t)dut->io_y_out_0_0);
  observed.push_back((int32_t)dut->io_y_out_0_1);
  observed.push_back((int32_t)dut->io_y_out_0_2);
  observed.push_back((int32_t)dut->io_y_out_0_3);
  observed.push_back((int32_t)dut->io_y_out_0_4);
  observed.push_back((int32_t)dut->io_y_out_0_5);
  observed.push_back((int32_t)dut->io_y_out_0_6);
  observed.push_back((int32_t)dut->io_y_out_0_7);
  observed.push_back((int32_t)dut->io_y_out_0_8);
  observed.push_back((int32_t)dut->io_y_out_0_9);
  observed.push_back((int32_t)dut->io_y_out_0_10);
  observed.push_back((int32_t)dut->io_y_out_0_11);
  observed.push_back((int32_t)dut->io_y_out_0_12);
  observed.push_back((int32_t)dut->io_y_out_0_13);
  observed.push_back((int32_t)dut->io_y_out_0_14);
  observed.push_back((int32_t)dut->io_y_out_0_15);
  observed.push_back((int32_t)dut->io_y_out_0_16);
  observed.push_back((int32_t)dut->io_y_out_0_17);
  observed.push_back((int32_t)dut->io_y_out_0_18);
  observed.push_back((int32_t)dut->io_y_out_0_19);
  observed.push_back((int32_t)dut->io_y_out_0_20);
  observed.push_back((int32_t)dut->io_y_out_0_21);
  observed.push_back((int32_t)dut->io_y_out_0_22);
  observed.push_back((int32_t)dut->io_y_out_0_23);
  observed.push_back((int32_t)dut->io_y_out_0_24);
  observed.push_back((int32_t)dut->io_y_out_0_25);
  observed.push_back((int32_t)dut->io_y_out_0_26);
  observed.push_back((int32_t)dut->io_y_out_0_27);
  observed.push_back((int32_t)dut->io_y_out_0_28);
  observed.push_back((int32_t)dut->io_y_out_0_29);
  observed.push_back((int32_t)dut->io_y_out_0_30);
  observed.push_back((int32_t)dut->io_y_out_0_31);
  observed.push_back((int32_t)dut->io_y_out_0_32);
  observed.push_back((int32_t)dut->io_y_out_0_33);
  observed.push_back((int32_t)dut->io_y_out_0_34);
  observed.push_back((int32_t)dut->io_y_out_0_35);
  observed.push_back((int32_t)dut->io_y_out_1_0);
  observed.push_back((int32_t)dut->io_y_out_1_1);
  observed.push_back((int32_t)dut->io_y_out_1_2);
  observed.push_back((int32_t)dut->io_y_out_1_3);
  observed.push_back((int32_t)dut->io_y_out_1_4);
  observed.push_back((int32_t)dut->io_y_out_1_5);
  observed.push_back((int32_t)dut->io_y_out_1_6);
  observed.push_back((int32_t)dut->io_y_out_1_7);
  observed.push_back((int32_t)dut->io_y_out_1_8);
  observed.push_back((int32_t)dut->io_y_out_1_9);
  observed.push_back((int32_t)dut->io_y_out_1_10);
  observed.push_back((int32_t)dut->io_y_out_1_11);
  observed.push_back((int32_t)dut->io_y_out_1_12);
  observed.push_back((int32_t)dut->io_y_out_1_13);
  observed.push_back((int32_t)dut->io_y_out_1_14);
  observed.push_back((int32_t)dut->io_y_out_1_15);
  observed.push_back((int32_t)dut->io_y_out_1_16);
  observed.push_back((int32_t)dut->io_y_out_1_17);
  observed.push_back((int32_t)dut->io_y_out_1_18);
  observed.push_back((int32_t)dut->io_y_out_1_19);
  observed.push_back((int32_t)dut->io_y_out_1_20);
  observed.push_back((int32_t)dut->io_y_out_1_21);
  observed.push_back((int32_t)dut->io_y_out_1_22);
  observed.push_back((int32_t)dut->io_y_out_1_23);
  observed.push_back((int32_t)dut->io_y_out_1_24);
  observed.push_back((int32_t)dut->io_y_out_1_25);
  observed.push_back((int32_t)dut->io_y_out_1_26);
  observed.push_back((int32_t)dut->io_y_out_1_27);
  observed.push_back((int32_t)dut->io_y_out_1_28);
  observed.push_back((int32_t)dut->io_y_out_1_29);
  observed.push_back((int32_t)dut->io_y_out_1_30);
  observed.push_back((int32_t)dut->io_y_out_1_31);
  observed.push_back((int32_t)dut->io_y_out_1_32);
  observed.push_back((int32_t)dut->io_y_out_1_33);
  observed.push_back((int32_t)dut->io_y_out_1_34);
  observed.push_back((int32_t)dut->io_y_out_1_35);
  observed.push_back((int32_t)dut->io_y_out_2_0);
  observed.push_back((int32_t)dut->io_y_out_2_1);
  observed.push_back((int32_t)dut->io_y_out_2_2);
  observed.push_back((int32_t)dut->io_y_out_2_3);
  observed.push_back((int32_t)dut->io_y_out_2_4);
  observed.push_back((int32_t)dut->io_y_out_2_5);
  observed.push_back((int32_t)dut->io_y_out_2_6);
  observed.push_back((int32_t)dut->io_y_out_2_7);
  observed.push_back((int32_t)dut->io_y_out_2_8);
  observed.push_back((int32_t)dut->io_y_out_2_9);
  observed.push_back((int32_t)dut->io_y_out_2_10);
  observed.push_back((int32_t)dut->io_y_out_2_11);
  observed.push_back((int32_t)dut->io_y_out_2_12);
  observed.push_back((int32_t)dut->io_y_out_2_13);
  observed.push_back((int32_t)dut->io_y_out_2_14);
  observed.push_back((int32_t)dut->io_y_out_2_15);
  observed.push_back((int32_t)dut->io_y_out_2_16);
  observed.push_back((int32_t)dut->io_y_out_2_17);
  observed.push_back((int32_t)dut->io_y_out_2_18);
  observed.push_back((int32_t)dut->io_y_out_2_19);
  observed.push_back((int32_t)dut->io_y_out_2_20);
  observed.push_back((int32_t)dut->io_y_out_2_21);
  observed.push_back((int32_t)dut->io_y_out_2_22);
  observed.push_back((int32_t)dut->io_y_out_2_23);
  observed.push_back((int32_t)dut->io_y_out_2_24);
  observed.push_back((int32_t)dut->io_y_out_2_25);
  observed.push_back((int32_t)dut->io_y_out_2_26);
  observed.push_back((int32_t)dut->io_y_out_2_27);
  observed.push_back((int32_t)dut->io_y_out_2_28);
  observed.push_back((int32_t)dut->io_y_out_2_29);
  observed.push_back((int32_t)dut->io_y_out_2_30);
  observed.push_back((int32_t)dut->io_y_out_2_31);
  observed.push_back((int32_t)dut->io_y_out_2_32);
  observed.push_back((int32_t)dut->io_y_out_2_33);
  observed.push_back((int32_t)dut->io_y_out_2_34);
  observed.push_back((int32_t)dut->io_y_out_2_35);
  observed.push_back((int32_t)dut->io_y_out_3_0);
  observed.push_back((int32_t)dut->io_y_out_3_1);
  observed.push_back((int32_t)dut->io_y_out_3_2);
  observed.push_back((int32_t)dut->io_y_out_3_3);
  observed.push_back((int32_t)dut->io_y_out_3_4);
  observed.push_back((int32_t)dut->io_y_out_3_5);
  observed.push_back((int32_t)dut->io_y_out_3_6);
  observed.push_back((int32_t)dut->io_y_out_3_7);
  observed.push_back((int32_t)dut->io_y_out_3_8);
  observed.push_back((int32_t)dut->io_y_out_3_9);
  observed.push_back((int32_t)dut->io_y_out_3_10);
  observed.push_back((int32_t)dut->io_y_out_3_11);
  observed.push_back((int32_t)dut->io_y_out_3_12);
  observed.push_back((int32_t)dut->io_y_out_3_13);
  observed.push_back((int32_t)dut->io_y_out_3_14);
  observed.push_back((int32_t)dut->io_y_out_3_15);
  observed.push_back((int32_t)dut->io_y_out_3_16);
  observed.push_back((int32_t)dut->io_y_out_3_17);
  observed.push_back((int32_t)dut->io_y_out_3_18);
  observed.push_back((int32_t)dut->io_y_out_3_19);
  observed.push_back((int32_t)dut->io_y_out_3_20);
  observed.push_back((int32_t)dut->io_y_out_3_21);
  observed.push_back((int32_t)dut->io_y_out_3_22);
  observed.push_back((int32_t)dut->io_y_out_3_23);
  observed.push_back((int32_t)dut->io_y_out_3_24);
  observed.push_back((int32_t)dut->io_y_out_3_25);
  observed.push_back((int32_t)dut->io_y_out_3_26);
  observed.push_back((int32_t)dut->io_y_out_3_27);
  observed.push_back((int32_t)dut->io_y_out_3_28);
  observed.push_back((int32_t)dut->io_y_out_3_29);
  observed.push_back((int32_t)dut->io_y_out_3_30);
  observed.push_back((int32_t)dut->io_y_out_3_31);
  observed.push_back((int32_t)dut->io_y_out_3_32);
  observed.push_back((int32_t)dut->io_y_out_3_33);
  observed.push_back((int32_t)dut->io_y_out_3_34);
  observed.push_back((int32_t)dut->io_y_out_3_35);
  observed.push_back((int32_t)dut->io_y_out_4_0);
  observed.push_back((int32_t)dut->io_y_out_4_1);
  observed.push_back((int32_t)dut->io_y_out_4_2);
  observed.push_back((int32_t)dut->io_y_out_4_3);
  observed.push_back((int32_t)dut->io_y_out_4_4);
  observed.push_back((int32_t)dut->io_y_out_4_5);
  observed.push_back((int32_t)dut->io_y_out_4_6);
  observed.push_back((int32_t)dut->io_y_out_4_7);
  observed.push_back((int32_t)dut->io_y_out_4_8);
  observed.push_back((int32_t)dut->io_y_out_4_9);
  observed.push_back((int32_t)dut->io_y_out_4_10);
  observed.push_back((int32_t)dut->io_y_out_4_11);
  observed.push_back((int32_t)dut->io_y_out_4_12);
  observed.push_back((int32_t)dut->io_y_out_4_13);
  observed.push_back((int32_t)dut->io_y_out_4_14);
  observed.push_back((int32_t)dut->io_y_out_4_15);
  observed.push_back((int32_t)dut->io_y_out_4_16);
  observed.push_back((int32_t)dut->io_y_out_4_17);
  observed.push_back((int32_t)dut->io_y_out_4_18);
  observed.push_back((int32_t)dut->io_y_out_4_19);
  observed.push_back((int32_t)dut->io_y_out_4_20);
  observed.push_back((int32_t)dut->io_y_out_4_21);
  observed.push_back((int32_t)dut->io_y_out_4_22);
  observed.push_back((int32_t)dut->io_y_out_4_23);
  observed.push_back((int32_t)dut->io_y_out_4_24);
  observed.push_back((int32_t)dut->io_y_out_4_25);
  observed.push_back((int32_t)dut->io_y_out_4_26);
  observed.push_back((int32_t)dut->io_y_out_4_27);
  observed.push_back((int32_t)dut->io_y_out_4_28);
  observed.push_back((int32_t)dut->io_y_out_4_29);
  observed.push_back((int32_t)dut->io_y_out_4_30);
  observed.push_back((int32_t)dut->io_y_out_4_31);
  observed.push_back((int32_t)dut->io_y_out_4_32);
  observed.push_back((int32_t)dut->io_y_out_4_33);
  observed.push_back((int32_t)dut->io_y_out_4_34);
  observed.push_back((int32_t)dut->io_y_out_4_35);
  observed.push_back((int32_t)dut->io_y_out_5_0);
  observed.push_back((int32_t)dut->io_y_out_5_1);
  observed.push_back((int32_t)dut->io_y_out_5_2);
  observed.push_back((int32_t)dut->io_y_out_5_3);
  observed.push_back((int32_t)dut->io_y_out_5_4);
  observed.push_back((int32_t)dut->io_y_out_5_5);
  observed.push_back((int32_t)dut->io_y_out_5_6);
  observed.push_back((int32_t)dut->io_y_out_5_7);
  observed.push_back((int32_t)dut->io_y_out_5_8);
  observed.push_back((int32_t)dut->io_y_out_5_9);
  observed.push_back((int32_t)dut->io_y_out_5_10);
  observed.push_back((int32_t)dut->io_y_out_5_11);
  observed.push_back((int32_t)dut->io_y_out_5_12);
  observed.push_back((int32_t)dut->io_y_out_5_13);
  observed.push_back((int32_t)dut->io_y_out_5_14);
  observed.push_back((int32_t)dut->io_y_out_5_15);
  observed.push_back((int32_t)dut->io_y_out_5_16);
  observed.push_back((int32_t)dut->io_y_out_5_17);
  observed.push_back((int32_t)dut->io_y_out_5_18);
  observed.push_back((int32_t)dut->io_y_out_5_19);
  observed.push_back((int32_t)dut->io_y_out_5_20);
  observed.push_back((int32_t)dut->io_y_out_5_21);
  observed.push_back((int32_t)dut->io_y_out_5_22);
  observed.push_back((int32_t)dut->io_y_out_5_23);
  observed.push_back((int32_t)dut->io_y_out_5_24);
  observed.push_back((int32_t)dut->io_y_out_5_25);
  observed.push_back((int32_t)dut->io_y_out_5_26);
  observed.push_back((int32_t)dut->io_y_out_5_27);
  observed.push_back((int32_t)dut->io_y_out_5_28);
  observed.push_back((int32_t)dut->io_y_out_5_29);
  observed.push_back((int32_t)dut->io_y_out_5_30);
  observed.push_back((int32_t)dut->io_y_out_5_31);
  observed.push_back((int32_t)dut->io_y_out_5_32);
  observed.push_back((int32_t)dut->io_y_out_5_33);
  observed.push_back((int32_t)dut->io_y_out_5_34);
  observed.push_back((int32_t)dut->io_y_out_5_35);
  observed.push_back((int32_t)dut->io_y_out_6_0);
  observed.push_back((int32_t)dut->io_y_out_6_1);
  observed.push_back((int32_t)dut->io_y_out_6_2);
  observed.push_back((int32_t)dut->io_y_out_6_3);
  observed.push_back((int32_t)dut->io_y_out_6_4);
  observed.push_back((int32_t)dut->io_y_out_6_5);
  observed.push_back((int32_t)dut->io_y_out_6_6);
  observed.push_back((int32_t)dut->io_y_out_6_7);
  observed.push_back((int32_t)dut->io_y_out_6_8);
  observed.push_back((int32_t)dut->io_y_out_6_9);
  observed.push_back((int32_t)dut->io_y_out_6_10);
  observed.push_back((int32_t)dut->io_y_out_6_11);
  observed.push_back((int32_t)dut->io_y_out_6_12);
  observed.push_back((int32_t)dut->io_y_out_6_13);
  observed.push_back((int32_t)dut->io_y_out_6_14);
  observed.push_back((int32_t)dut->io_y_out_6_15);
  observed.push_back((int32_t)dut->io_y_out_6_16);
  observed.push_back((int32_t)dut->io_y_out_6_17);
  observed.push_back((int32_t)dut->io_y_out_6_18);
  observed.push_back((int32_t)dut->io_y_out_6_19);
  observed.push_back((int32_t)dut->io_y_out_6_20);
  observed.push_back((int32_t)dut->io_y_out_6_21);
  observed.push_back((int32_t)dut->io_y_out_6_22);
  observed.push_back((int32_t)dut->io_y_out_6_23);
  observed.push_back((int32_t)dut->io_y_out_6_24);
  observed.push_back((int32_t)dut->io_y_out_6_25);
  observed.push_back((int32_t)dut->io_y_out_6_26);
  observed.push_back((int32_t)dut->io_y_out_6_27);
  observed.push_back((int32_t)dut->io_y_out_6_28);
  observed.push_back((int32_t)dut->io_y_out_6_29);
  observed.push_back((int32_t)dut->io_y_out_6_30);
  observed.push_back((int32_t)dut->io_y_out_6_31);
  observed.push_back((int32_t)dut->io_y_out_6_32);
  observed.push_back((int32_t)dut->io_y_out_6_33);
  observed.push_back((int32_t)dut->io_y_out_6_34);
  observed.push_back((int32_t)dut->io_y_out_6_35);
  observed.push_back((int32_t)dut->io_y_out_7_0);
  observed.push_back((int32_t)dut->io_y_out_7_1);
  observed.push_back((int32_t)dut->io_y_out_7_2);
  observed.push_back((int32_t)dut->io_y_out_7_3);
  observed.push_back((int32_t)dut->io_y_out_7_4);
  observed.push_back((int32_t)dut->io_y_out_7_5);
  observed.push_back((int32_t)dut->io_y_out_7_6);
  observed.push_back((int32_t)dut->io_y_out_7_7);
  observed.push_back((int32_t)dut->io_y_out_7_8);
  observed.push_back((int32_t)dut->io_y_out_7_9);
  observed.push_back((int32_t)dut->io_y_out_7_10);
  observed.push_back((int32_t)dut->io_y_out_7_11);
  observed.push_back((int32_t)dut->io_y_out_7_12);
  observed.push_back((int32_t)dut->io_y_out_7_13);
  observed.push_back((int32_t)dut->io_y_out_7_14);
  observed.push_back((int32_t)dut->io_y_out_7_15);
  observed.push_back((int32_t)dut->io_y_out_7_16);
  observed.push_back((int32_t)dut->io_y_out_7_17);
  observed.push_back((int32_t)dut->io_y_out_7_18);
  observed.push_back((int32_t)dut->io_y_out_7_19);
  observed.push_back((int32_t)dut->io_y_out_7_20);
  observed.push_back((int32_t)dut->io_y_out_7_21);
  observed.push_back((int32_t)dut->io_y_out_7_22);
  observed.push_back((int32_t)dut->io_y_out_7_23);
  observed.push_back((int32_t)dut->io_y_out_7_24);
  observed.push_back((int32_t)dut->io_y_out_7_25);
  observed.push_back((int32_t)dut->io_y_out_7_26);
  observed.push_back((int32_t)dut->io_y_out_7_27);
  observed.push_back((int32_t)dut->io_y_out_7_28);
  observed.push_back((int32_t)dut->io_y_out_7_29);
  observed.push_back((int32_t)dut->io_y_out_7_30);
  observed.push_back((int32_t)dut->io_y_out_7_31);
  observed.push_back((int32_t)dut->io_y_out_7_32);
  observed.push_back((int32_t)dut->io_y_out_7_33);
  observed.push_back((int32_t)dut->io_y_out_7_34);
  observed.push_back((int32_t)dut->io_y_out_7_35);

  write_ints(dir + "/observed_verilator.txt", observed);
  std::cout << "[case12] wrote " << observed.size() << " values, cycles=" << cyc << "\n";

  tfp->close();
  delete tfp;
  delete dut;
  return 0;
}
